### ISSUE TITLE
Attachments arrive via email with invalid header.

### ISSUE THREAD

**Issue by talllguy** [xiao8579/QuickCapture-Testing#13] opened 2020-04-09 18:22 UTC
I discovered an issue with the attachment handling.

## Scenario
Using Interomat: get QC data, filter on attribute, send Gmail with attachment from QC as attachment.
![image](https://user-images.githubusercontent.com/1827881/78927353-c053de80-7a6c-11ea-95c2-55dca8ae9664.png)

## Result
Get email successfully ✅ 
Photo attachment has invalid format ❌ 
![image](https://user-images.githubusercontent.com/1827881/78927116-4facc200-7a6c-11ea-9270-28bf46a7b2da.png)

**Comment by talllguy** [comment] 2020-04-09 18:24
I wonder if this has something to do with the token of the HTTP request. Here's the input for the _HTTP add file_ module:

```
[
    {
        "url": "https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/QuickCapture_OSM_Demo_02173e8bc0ac47db80508c3c143f0488/FeatureServer/2/8/attachments/5",
        "method": "get",
        "shareCookies": false
    }
]
```

Notice there is no token? Should that be pulled from the QC project? I will fiddle around with pulling that.

**Comment by talllguy** [comment] 2020-04-09 18:26
I bet this will work.
![image](https://user-images.githubusercontent.com/1827881/78928116-0d848000-7a6e-11ea-8c9e-8c10dec67c4a.png)

**Comment by talllguy** [comment] 2020-04-09 18:28
🚀 🍾 That fixed it!

![image](https://user-images.githubusercontent.com/1827881/78928334-6d7b2680-7a6e-11ea-9f55-8c8fed781935.png)

**Comment by engelm1324** [comment] 2020-04-09 18:33
This worked for me to get the attachments.  Without the token the attachment will not work for me.

**Comment by Leandermen** [comment] 2020-04-09 19:36
Reproducing the workflow it works for me too even works with uploading to onedrive for business.

![image](https://user-images.githubusercontent.com/6208975/78933771-cc916900-7a77-11ea-8a30-ac9490a7a729.png)

**Comment by engelm1324** [comment] 2020-04-09 19:58
> Reproducing the workflow it works for me too even works with uploading to onedrive for business.
> 
> ![image](https://user-images.githubusercontent.com/6208975/78933771-cc916900-7a77-11ea-8a30-ac9490a7a729.png)

I did a version of this, but with Office365 email.

**Comment by xiao8579** [comment] 2020-04-13 19:07
Bug fixed in QuickCapture Intergromat app. Closing.

**Closed as completed by xiao8579** 2020-04-13 19:07 UTC
Labels: A - Bug, Fixed
